import { Router, type IRouter } from "express";
import healthRouter, { v1SystemRouter } from "./health";
import authRouter from "./auth";
import searchRouter from "./search";
import conversationsRouter from "./conversations";
import languagesRouter from "./languages";
import legalProvidersRouter from "./legal-providers";
import contractsRouter from "./contracts";
import bookingLegalRouter from "./booking-legal";
import disputesRouter from "./disputes";
import notificationsRouter from "./notifications";
import transactionsRouter from "./transactions";
import adminTransactionsRouter from "./admin-transactions";
import paymentsRouter from "./payments";
import subscriptionsRouter from "./subscriptions";
import advertisementsRouter from "./advertisements";
import commissionsRouter from "./commissions";
import reviewsRouter from "./reviews";
import verificationsRouter from "./verifications";
import serviceProvidersRouter from "./service-providers";
import marketplaceListingsRouter from "./marketplace-listings";
import marketplaceInvestorsRouter from "./marketplace-investors";
import adminConsoleRouter from "./admin-console";
import adminUsersRouter from "./admin-users";
import adminListingsRouter from "./admin-listings";
import adminCategoriesRouter from "./admin-categories";
import adminSupportRouter from "./admin-support";
import dashboardsRouter from "./dashboards";
import helpRouter from "./help";
import filesRouter from "./files";
import adminAuditLogsRouter from "./admin-audit-logs";
import docsRouter from "./docs";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/v1", v1SystemRouter);
router.use(docsRouter);
router.use(authRouter);
router.use(searchRouter);
router.use(conversationsRouter);
router.use(languagesRouter);
router.use(legalProvidersRouter);
router.use(contractsRouter);
router.use(bookingLegalRouter);
router.use(disputesRouter);
router.use(notificationsRouter);
router.use(transactionsRouter);
router.use(adminTransactionsRouter);
router.use(paymentsRouter);
router.use(subscriptionsRouter);
router.use(advertisementsRouter);
router.use(commissionsRouter);
router.use(reviewsRouter);
router.use(verificationsRouter);
router.use(serviceProvidersRouter);
router.use(marketplaceListingsRouter);
router.use(marketplaceInvestorsRouter);
router.use(adminConsoleRouter);
router.use(adminUsersRouter);
router.use(adminListingsRouter);
router.use(adminCategoriesRouter);
router.use(adminSupportRouter);
router.use(adminAuditLogsRouter);
router.use(dashboardsRouter);
router.use(helpRouter);
router.use(filesRouter);
/** Versioned file aliases: /api/v1/files/... */
router.use("/v1", filesRouter);

export default router;
